### ISSUE TITLE
Hidden file input styling bug in mobile Safari

### ISSUE THREAD

**Issue by timiyay** [thefrontside/emberx-file-input#16]
Nice work on this component, I've found it to be a breeze to work with.

When using this component with iOS9 Safari, I found that the `width: 0` property on the hidden `<input type="file">` element wasn't fully preventing the element having width.

Instead, I was left with a whitespace gutter down the right side of the page.

To fix this I had to add `max-width: 0` to the `.x-file--input` CSS class.

It could be worth chucking this in the component's  default CSS, if other people can reproduce this.

**Comment by cowboyd** [comment]
Seems reasonable. Care to submit a PR?

**Comment by timiyay** [comment]
@cowboyd Yep will do

**Comment by Robdel12** [comment]
Thanks for the PR! This was closed with #17
