### ISSUE TITLE
Limited support

### ISSUE THREAD

**Issue by ramoncaldeira** [thefrontside/emberx-file-input#19]
I'm working on a project that uses ember 1.11.1 and this component didn't work for it. Turns out that this component uses the `hasBlock` directive, introduced with ember 1.13. Warnings about this kind of things would be welcome!

**Comment by cowboyd** [comment]
Thanks for bring this to our attention. Do you have a suggested workaround?

**Comment by ramoncaldeira** [comment]
Yes, take a look at this commit from ember-paper https://github.com/peec/ember-paper/commit/218c0815ab5b01b8181a52ba09cfad3136a474af

**Comment by cowboyd** [comment]
Thanks! Would be really amenableto accepting this in a PR.

**Comment by Robdel12** [comment]
I feel like we're far enough removed from 1.11 that we don't have to support it. If anyone doesn't agree we can reopen and discuss :)
