### ISSUE TITLE
Release on npm ?

### ISSUE THREAD

**Issue by ksol** [thefrontside/emberx-file-input#2]
Unless I'm missing something, this component is not on npm (https://www.npmjs.com/package/emberx-file-input), while the other `emberx-*` (or at least `x-select`) are. It would be nice to have it there too : )

Thanks for the component !

**Comment by Robdel12** [comment]
It's sort of intentional, we're not entirely ready for the public to use this, _yet_. 

We should (hopefully) have a release out sometime next week :)

**Comment by ksol** [comment]
Good to know! Those helpers have been useful to me, so if you need help on some level (technical or doc, anything), please let me know. Have a nice day !

**Comment by Robdel12** [comment]
Annnnd it's happened! :D :tada: v1.0.0 is on NPM now.
