### ISSUE TITLE
Action not firing when selecting the same file twice

### ISSUE THREAD

**Issue by netes** [thefrontside/emberx-file-input#23]
Hi,
Thanks for great addon!
I've found small issue when you select the same file twice - action is not firing on the second one. I'm using your addon for image cropper and I want the user to be able to select same file twice, right now it's impossible.

**Comment by netes** [comment]
OK, I found a solution, it's not related to the addon. To allow uploading same file twice `input` has to be reset, like this for example: `document.getElementById('uploader').reset()` and the `input` itself should be wrapped in `form` tag to allow resetting.

**Comment by Robdel12** [comment]
This does bring up an interesting question: Would it be helpful to have a reset action?

**Comment by netes** [comment]
Actually I made a PR with a little better solution than previous one. So let's discuss there :)

**Comment by Robdel12** [comment]
Hey @netes, we haven't forgotten about this. It's actually spurred a lot of discussion internally but we've failed to radiate that discussion out.

I have a branch (https://github.com/thefrontside/emberx-file-input/tree/netes-allow-input-reset) that has this change. @cowboyd, it's been a little while, what were your thoughts again? 

Also I'm not sure how to test this. Maybe we abstract the resetting the value of the input into a method on the component and stub it for testing?
