### ISSUE TITLE
Overriding init without calling this._super is deprecated

### ISSUE THREAD

**Issue by chaitanyya** [thefrontside/emberx-file-input#27]
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/Chaitanya/Developer/Harvard/DotPlotApp/DotPlot/node_modules/ember-cli/lib/models/addon.js:896:27)

```
Following error shows after installing the addon.

**Comment by chaitanyya** [comment]
Updating the ember-cli-htmlbars to latest version fixed the issue.

**Comment by Robdel12** [comment]
Hey @chaitanyya! thanks for bringing this up! I've opened a PR that upgrades all of our dependencies. If you'd like to give it a try to see if anything else pops up that'd be great :)
