### ISSUE TITLE
Importing emberx-file-input in an addon

### ISSUE THREAD

**Issue by xcambar** [thefrontside/emberx-file-input#30]
Unfortunately, #28 reverts #26  (aka, remove `ember-cli-import-polyfill`, mostly) which allowed the addon to be imported from another addon.

It breaks an important use case for us, as we import this addon from other (private) addons. I'm taking the opportunity to start the discussion here about what should be the best approach, considering that ignoring this use case was intentional.

FYI, the polyfill is meant for an upcoming feature in Ember 2.7 that allows nested addons. See https://github.com/ember-cli/ember-cli/pull/6043 for the implementation.

ping @Robdel12 @cowboyd

**Comment by Robdel12** [comment]
Woops, at first I thought it went out with a release. Thankfully it didn't :) 

Thanks for bringing this to my attention (_again_), I opened a PR and once those tests pass I'm going to merge it. 🎉
