### ISSUE TITLE
Setting file format

### ISSUE THREAD

**Issue by lkgarrison** [thefrontside/emberx-file-input#32]
With the default file picker, <input type='file'> you can specify the file formats accepted via the "accept" attribute. Is this a possible feature for emberx-file-input?

**Comment by cowboyd** [comment]
It should be. Are you not able to do this? https://github.com/thefrontside/emberx-file-input/blob/master/addon/components/x-file-input.js#L6

**Comment by Robdel12** [comment]
That should work, but it's totally undocumented :) Added a documentation label & the 1.1.0 milestone to make sure it's added to the README

**Comment by lkgarrison** [comment]
I can confirm it does indeed work. Thanks!

**Comment by Robdel12** [comment]
I'm going to reopen this since we still need to document it
