### ISSUE TITLE
width: 0px on hidden file input is treated like not there

### ISSUE THREAD

**Issue by RobIsHere** [thefrontside/emberx-file-input#33]
When i place a custom styled label inside it takes up the same space like without width: 0px.
Even when the label content is narrower. This is only visible when positioning adjacent to some right side neighbour stuff and your "margin" grows larger than expected.

My fix is to make width: 1px;

The file input is not shown anyways because of the height 0px

Browser: current Chrome on Windows

**Comment by Robdel12** [comment]
Can I get an [ember twiddle](http://ember-twiddle.com) example? I'm having a hard time visualizing what's going on :)

**Comment by RobIsHere** [comment]
Ok. Here it is: https://ember-twiddle.com/f258ce5ab1d1d163067fa1c3782b874c?openFiles=templates.application.hbs%2C

The red and blue bars should be next to each other because there is no margin at all.
It is just the existence of the 0x0px file input, that is shifting it away by 250px. (Chrome!)

**Comment by Robdel12** [comment]
Woah, excellent catch of a browser bug! I can't get ember twiddle to play nicely with Safari but Chrome is misbehaving. Firefox is fine! I'll make a PR, merge,  and cut the next release
