### ISSUE TITLE
Publish New Release Soon?

### ISSUE THREAD

**Issue by maprules1000** [thefrontside/emberx-file-input#42]
Any chance a new release will be published soon with the 16 new commits since 1.0.0?

**Comment by Robdel12** [comment]
Closed with https://github.com/thefrontside/emberx-file-input/commit/a7ec862cabacf15a0fcdc206f4813aabeba90887


Sorry it took so long! I was going to cut a release a little while ago but travis CI started failing builds and I didn't have time to debug travis until now.
