### ISSUE TITLE
New release with testing helpers

### ISSUE THREAD

**Issue by benshine** [thefrontside/emberx-file-input#53]
https://github.com/thefrontside/emberx-file-input/pull/49 is fantastic -- can you make a release with it?

**Comment by Robdel12** [comment]
I could get to this tonight after work. Anyone from @thefrontside/staff have time before?

**Comment by jpongin** [comment]
When do you plan to release this fix? Thanks :)

**Comment by cowboyd** [comment]
Released as version [1.2.0](https://www.npmjs.com/package/emberx-file-input)
