### ISSUE TITLE
Can I open camera in android?

### ISSUE THREAD

**Issue by bloodknight2010** [thefrontside/emberx-file-input#61]
Hello,

Now i use the x-file-input for android app using emberjs. I want to know when I click x-file-input, can open phone camera view? If it is got How to configuration in my app?
Pls help me.

**Comment by Robdel12** [comment]
I haven't tested this but it looks like you can pass `accept="image/*;capture=camera"` to open the camera from a file input https://stackoverflow.com/questions/7676036/can-you-launch-the-native-camera-app-from-an-html-5-web-app
